"""
Tutor API routes.

Endpoints
---------
POST /api/v1/tutor/explain
    Accept a TutorContext payload, pass it to TutorService, and return
    a TutorResponse.  Phase 1 returns a deterministic placeholder.
"""

from fastapi import APIRouter
from fastapi.responses import JSONResponse

from app.core.logging import get_logger
from app.schemas.tutor import TutorContext, TutorResponse
from app.services.tutor_service import TutorService

logger = get_logger(__name__)

router = APIRouter(prefix="/tutor", tags=["tutor"])

# Instantiate the service once; it is stateless so one instance is fine.
_tutor_service = TutorService()


@router.post(
    "/explain",
    response_model=TutorResponse,
    summary="Generate a tutoring explanation",
    description=(
        "Accepts a TutorContext payload from the LearnTrace backend and "
        "returns a structured TutorResponse.  "
        "**Phase 1**: returns a deterministic placeholder response. "
        "**Future phases**: response will be generated by an LLM."
    ),
)
def explain(context: TutorContext) -> TutorResponse:
    """
    Generate a tutoring explanation for a learner's incorrect answer.

    - **context**: Full TutorContext as supplied by the LearnTrace backend.
    """
    logger.info(
        "POST /tutor/explain | competency=%s question=%s",
        context.competency.id,
        context.question.id,
    )
    return _tutor_service.explain(context)
