"""
Pydantic schemas for the AI Tutor API.

These are *domain / API schemas* only.
They are NOT tied to any database ORM.

Request side
------------
TutorContext is the payload the LearnTrace backend will eventually send
to the AI Tutor.  It carries everything the tutor needs to produce a
personalised explanation:

  - The competency being assessed.
  - The question that was posed to the learner.
  - What the learner answered.
  - What the correct answer is.
  - The gap or misconception detected by the LearnTrace mastery engine.

Response side
-------------
TutorResponse contains all tutor output fields.  In Phase 1 these are
filled with deterministic placeholder text.  Later phases will populate
them from a real LLM.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# ------------------------------------------------------------------ #
# Request schemas
# ------------------------------------------------------------------ #


class Competency(BaseModel):
    """Identifies the competency being assessed."""

    id: str = Field(..., description="Machine-readable competency identifier.")
    name: str = Field(..., description="Human-readable competency name.")


class Question(BaseModel):
    """The question that was presented to the learner."""

    id: str = Field(..., description="Unique question identifier.")
    text: str = Field(..., description="Full question text.")
    options: list[str] = Field(
        ...,
        min_length=2,
        description="Answer options presented to the learner.",
    )


class DetectedGap(BaseModel):
    """A gap or misconception identified by the LearnTrace mastery engine."""

    description: str = Field(
        ...,
        description="Plain-language description of the detected gap.",
    )


class TutorContext(BaseModel):
    """
    Full context payload sent from LearnTrace to the AI Tutor.

    This is the authoritative source of truth for a single tutoring
    interaction.  The LearnTrace backend populates all fields; the AI
    Tutor must not re-derive mastery, correctness, or prerequisites.
    """

    competency: Competency
    question: Question
    learner_answer: str = Field(
        ...,
        description="The option selected by the learner.",
    )
    correct_answer: str = Field(
        ...,
        description="The option that is correct.",
    )
    detected_gap: Optional[DetectedGap] = Field(
        default=None,
        description="Gap detected by LearnTrace; may be absent if none was identified.",
    )


# ------------------------------------------------------------------ #
# Response schemas
# ------------------------------------------------------------------ #


class PracticeQuestion(BaseModel):
    """A follow-up practice question generated by the tutor."""

    question: str = Field(..., description="Practice question text.")
    options: list[str] = Field(
        ...,
        min_length=2,
        description="Answer options for the practice question.",
    )
    correct_option: str = Field(
        ...,
        description="The correct option for the practice question.",
    )
    explanation: str = Field(
        ...,
        description="Explanation of why this option is correct.",
    )


class TutorResponse(BaseModel):
    """
    Structured output produced by the AI Tutor for one tutoring interaction.

    In Phase 1 all fields are filled with deterministic placeholder text.
    In future phases an LLM will populate these fields.
    """

    explanation: str = Field(
        ...,
        description="Detailed explanation of the learner's mistake.",
    )
    simple_explanation: str = Field(
        ...,
        description="ELI5-style simplified explanation of the concept.",
    )
    worked_example: str = Field(
        ...,
        description="A concrete worked example illustrating the concept.",
    )
    practice_question: PracticeQuestion = Field(
        ...,
        description="A new practice question to reinforce the concept.",
    )
